### ISSUE TITLE
Multiple "Show full transcript" buttons

### ISSUE THREAD

**Issue by john-mantas** [adocasts/adocasts#55]
In lessons that have transcript, if the user clicks on the "SHOW FULL TRANSCRIPT" then multiple "instances" of the button is visible and stacked. Also, the last lines are hidden by the `.transcript-cutoff` background.

![image](https://github.com/adocasts/adocasts/assets/35237226/8cc0a061-7434-4160-9f7a-bdaa4aed134b)

There are many elements with the below markup in the transcript

```
<div class="transcript-cutoff">
  <button type="button" id="transcriptCutoffBtn" @click="onTranscriptToggle"></button>
</div>
```

**Comment by tomgobich** [comment]
I believe this should now be fixed across all lessons with a transcript. This was a side-effect of a previously resolved bug where the `HtmlParser.highlight()` result got persisted into database on the post's `body` column. So, each time this bug occurred it'd store another instance of the "Show/Hide Transcript" toggle. 

The fix was to go through the affected posts and resave them.
